### ISSUE TITLE
[Frontend] Scene placement. Left of  Scene and right of Chat needs to be same margin

### ISSUE THREAD

**Issue by vitarico1** [PretzelDAO/Bakery-Frontend#14]

**Comment by a-rohr** [comment]
# Current placemenet uneven margins
![image](https://user-images.githubusercontent.com/46085397/169986858-064e73f3-ad69-4cd5-8ebb-296b1e8703e7.png)

# Desired Placement equal margins
![image](https://user-images.githubusercontent.com/46085397/169986375-7cf6b3c0-beae-4f98-9e9a-c81e22f4297d.png)
