### ISSUE TITLE
BUG Sugar Pretzel Mint (not gasless) was successful but Frontend got stuck

### ISSUE THREAD

**Issue by vitarico1** [PretzelDAO/Bakery-Frontend#58]
![Image](https://user-images.githubusercontent.com/101890438/170479306-0968e5ab-4a09-47c0-a695-aac67801af2b.png)

![Image](https://user-images.githubusercontent.com/101890438/170479354-081fd10c-3b32-40e5-a9a8-88812f773492.png)

https://kovan.etherscan.io/tx/0xcdcc16b59dc2ebfbc20e84df7652767e86ccb362245d8622f04948869c85b9d2

**Comment by tachysheurisko** [comment]
isnt reproducible, please elaborate @vitarico1
